# Generated by Django 5.0.3 on 2024-03-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_confort', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_econ', models.DecimalField(decimal_places=2, max_digits=5)),
                ('city', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('seat', models.CharField(max_length=4)),
                ('bed', models.CharField(max_length=4)),
            ],
        ),
    ]
